import { SiteChrome } from "@/components/site-chrome";

const sections = [
  {
    title: "Agreement",
    body: "These Terms of Service govern your use of SprayRate. By using SprayRate, you agree to these terms. If you do not agree, do not use the app.",
  },
  {
    title: "Beta and Future Releases",
    body: "SprayRate may be distributed as a beta, preview, test, or future production release. Features, pricing, workflows, and functionality may change, and bugs, errors, or interruptions may exist.",
  },
  {
    title: "As-Is Software",
    body: "SprayRate is provided as-is and as available, without warranties of any kind, to the maximum extent permitted by law.",
  },
  {
    title: "Verification Duties",
    body: "You are solely responsible for verifying every quote, estimate, rate, acreage value, product entry, field record, application record, weather snapshot, export, and generated output before relying on it.",
  },
  {
    title: "Operational and Regulatory Responsibility",
    body: "SprayRate does not provide legal, regulatory, agronomic, or operational approval. You remain solely responsible for chemical selections, application rates, operational decisions, recordkeeping obligations, and compliance with applicable laws and restrictions.",
  },
  {
    title: "Exports and Documentation Tools",
    body: "PDFs, exports, backups, and related records generated by SprayRate are documentation tools only. They do not guarantee regulatory compliance, audit success, or operational suitability.",
  },
  {
    title: "Limitation of Liability",
    body: "To the maximum extent permitted by law, SprayRate and its operators are not liable for indirect, incidental, consequential, special, or punitive damages, including lost profits, lost data, business interruption, crop loss, property damage, or regulatory consequences arising out of use of the app.",
  },
  {
    title: "Contact",
    body: "For terms questions or support, contact support@getsprayrate.com.",
  },
];

export default function TermsPage() {
  return (
    <SiteChrome
      eyebrow="Terms of Service"
      title="SprayRate Terms of Service"
      intro="Last updated June 22, 2026. These terms are a public-facing summary of the current SprayRate usage terms during beta-stage release."
    >
      <section className="grid gap-5">
        {sections.map((section, index) => (
          <article
            key={section.title}
            className="glass-panel reveal-up p-7"
            style={{ animationDelay: `${index * 70}ms` }}
          >
            <h2 className="font-display text-2xl text-white">{section.title}</h2>
            <p className="mt-4 text-base leading-8 text-[var(--muted)]">{section.body}</p>
          </article>
        ))}
      </section>
    </SiteChrome>
  );
}
