import { SiteChrome } from "@/components/site-chrome";

const sections = [
  {
    title: "Agreement",
    body: "These Terms of Service govern your use of SprayRate and apply to beta users, TestFlight users, production users, and future App Store users. By accessing or using SprayRate, you agree to these terms. If you do not agree, do not use the app.",
  },
  {
    title: "Beta and Future Releases",
    body: "SprayRate may be distributed as a beta, preview, evaluation, test, pre-release, or production version. Features, pricing, subscription offerings, workflows, and functionality may change, and bugs, errors, or interruptions may exist.",
  },
  {
    title: "Operator and Contact",
    body: "SprayRate is currently operated by SpiderByte Labs. If SprayRate later begins operating through SpiderByte Labs LLC or another legal entity, these Terms may be updated to reflect that entity and its formal business details. For support, beta questions, or legal notices, contact support@getsprayrate.com or hello@spiderbytelabs.com.",
  },
  {
    title: "As-Is Software",
    body: "SprayRate is provided as-is and as available, with all faults, and without warranties of any kind, whether express, implied, or statutory, to the maximum extent permitted by law.",
  },
  {
    title: "Verification Duties",
    body: "You are solely responsible for verifying every quote, estimate, rate, acreage value, product entry, chemical selection, pricing assumption, field record, application record, weather snapshot, export, and generated output before relying on it.",
  },
  {
    title: "Operational and Regulatory Responsibility",
    body: "SprayRate does not provide legal, regulatory, agronomic, or operational approval. You remain solely responsible for chemical selections, application rates, operational decisions, recordkeeping obligations, and compliance with applicable laws and restrictions.",
  },
  {
    title: "Exports and Documentation Tools",
    body: "Application records, PDF exports, CSV exports, backups, and related records generated by SprayRate are documentation tools only. They do not guarantee regulatory compliance, audit success, or operational suitability.",
  },
  {
    title: "Limitation of Liability",
    body: "To the maximum extent permitted by law, SprayRate and its owners, operators, licensors, service providers, and affiliates are not liable for indirect, incidental, consequential, special, punitive, or enhanced damages, including lost profits, lost revenue, lost business, lost data, business interruption, crop loss, property damage, operational losses, or regulatory consequences arising out of use of the app.",
  },
  {
    title: "Governing Law and Venue",
    body: "These Terms and any dispute arising out of or related to SprayRate are governed by the laws of the State of North Carolina, without regard to conflict-of-law rules. To the extent permitted by law, the state and federal courts located in North Carolina will be the exclusive venue for disputes related to SprayRate.",
  },
];

export default function TermsPage() {
  return (
    <SiteChrome
      eyebrow="Terms of Service"
      title="SprayRate Terms of Service"
      intro="Version 1.1, last updated June 22, 2026. These terms summarize the current SprayRate usage terms during the beta-stage release cycle."
    >
      <section className="grid gap-5">
        {sections.map((section, index) => (
          <article
            key={section.title}
            className="glass-panel reveal-up p-7"
            style={{ animationDelay: `${index * 70}ms` }}
          >
            <h2 className="font-display text-2xl text-white">{section.title}</h2>
            <p className="mt-4 text-base leading-8 text-[var(--muted)]">{section.body}</p>
          </article>
        ))}
      </section>
    </SiteChrome>
  );
}
